/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#46674c",
        "inverse-surface": "#100e05",
        "on-secondary-fixed-variant": "#72554b",
        "error-dim": "#791903",
        "primary-dim": "#3a5a40",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fd795a",
        "on-tertiary": "#fff7f4",
        "secondary": "#75584e",
        "on-error": "#fff7f6",
        "on-primary": "#e8ffe8",
        "on-primary-fixed-variant": "#436348",
        "on-tertiary-container": "#552900",
        "surface-container-low": "#fbf3db",
        "tertiary-dim": "#824200",
        "surface-container-highest": "#ebe3c2",
        "on-primary-fixed": "#27462e",
        "background": "#fff9eb",
        "secondary-fixed": "#ffdbce",
        "secondary-dim": "#684d43",
        "tertiary-container": "#fda055",
        "on-background": "#37331c",
        "surface-container-high": "#f0e8cc",
        "outline-variant": "#bab294",
        "secondary-container": "#ffdbce",
        "surface-variant": "#ebe3c2",
        "surface-tint": "#46674c",
        "primary-container": "#c7ecca",
        "on-tertiary-fixed-variant": "#623000",
        "on-secondary": "#fff7f5",
        "on-surface-variant": "#655f46",
        "primary-fixed-dim": "#b9debc",
        "on-error-container": "#6e1400",
        "on-primary-container": "#39593f",
        "surface-dim": "#e3daba",
        "error": "#a73b21",
        "surface-container": "#f6eed3",
        "inverse-on-surface": "#a29d8c",
        "secondary-fixed-dim": "#f3ccbf",
        "outline": "#817b60",
        "on-surface": "#37331c",
        "tertiary-fixed-dim": "#ed9349",
        "on-tertiary-fixed": "#331600",
        "on-secondary-container": "#674b41",
        "tertiary-fixed": "#fda055",
        "surface-bright": "#fff9eb",
        "on-secondary-fixed": "#533930",
        "surface": "#fff9eb",
        "primary-fixed": "#c7ecca",
        "tertiary": "#934c00",
        "inverse-primary": "#cff5d2"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
